const constants = {
  product: {
    GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAILED: "GET_PRODUCT_FAILED",
    GET_PRODUCT_DETAILS_REQUEST: "GET_PRODUCT_DETAILS_REQUEST",
    GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
    GET_PRODUCT_DETAILS_FAILED: "GET_PRODUCT_DETAILS_FAILED",
  },
  category: {
    CATEGORY_GET_REQUEST: " CATEGORY_GET_REQUEST",
    CATEGORY_GET_SUCCESS: " CATEGORY_GET_SUCCESS",
    CATEGORY_GET_FAILED: " CATEGORY_GET_FAILED",
  },
  PRODUCTS_BY_CATEGORY_GET_REQUEST: "PRODUCTS_BY_CATEGORY_GET_REQUEST",
  PRODUCTS_BY_CATEGORY_GET_SUCCESS: "PRODUCTS_BY_CATEGORY_GET_SUCCESS",
  PRODUCTS_BY_CATEGORY_GET_FAILED: "PRODUCTS_BY_CATEGORY_GET_FAILED",
};
export default constants;
