const constants = {
  product: {
    GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAILED: "GET_PRODUCT_FAILED",
    GET_PRODUCT_DETAILS_REQUEST: "GET_PRODUCT_DETAILS_REQUEST",
    GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
    GET_PRODUCT_DETAILS_FAILED: "GET_PRODUCT_DETAILS_FAILED",
  },
};
export default constants;
